services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8090:8000"
    env_file:
      - .env.backend
    restart: unless-stopped
    networks:
      - web-bot-net

  sentinel:
    build:
      context: ../sentinelbot
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
    env_file:
      - .env.sentinel
    restart: unless-stopped
    networks:
      - web-bot-net

  frontend:
    image: ziyad188/web-bot:ftest
    ports:
      - "3090:80"
    restart: unless-stopped
    env_file:
      - .env.frontend
    networks:
      - web-bot-net

networks:
  web-bot-net:
    driver: bridge
    enable_ipv6: true
